/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CasaRouteImport } from './routes/casa'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as TareasRouteImport } from './routes/tareas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaRoute = CasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/casa': typeof CasaRoute
  '/focus': typeof FocusRoute
  '/sistema': typeof SistemaRoute
  '/tareas': typeof TareasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/casa': typeof CasaRoute
  '/focus': typeof FocusRoute
  '/sistema': typeof SistemaRoute
  '/tareas': typeof TareasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/casa': typeof CasaRoute
  '/focus': typeof FocusRoute
  '/sistema': typeof SistemaRoute
  '/tareas': typeof TareasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas'
    | '/biblioteca'
    | '/calendario'
    | '/casa'
    | '/focus'
    | '/sistema'
    | '/tareas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas'
    | '/biblioteca'
    | '/calendario'
    | '/casa'
    | '/focus'
    | '/sistema'
    | '/tareas'
  id:
    | '__root__'
    | '/'
    | '/areas'
    | '/biblioteca'
    | '/calendario'
    | '/casa'
    | '/focus'
    | '/sistema'
    | '/tareas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasRoute: typeof AreasRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CalendarioRoute: typeof CalendarioRoute
  CasaRoute: typeof CasaRoute
  FocusRoute: typeof FocusRoute
  SistemaRoute: typeof SistemaRoute
  TareasRoute: typeof TareasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa': {
      id: '/casa'
      path: '/casa'
      fullPath: '/casa'
      preLoaderRoute: typeof CasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasRoute: AreasRoute,
  BibliotecaRoute: BibliotecaRoute,
  CalendarioRoute: CalendarioRoute,
  CasaRoute: CasaRoute,
  FocusRoute: FocusRoute,
  SistemaRoute: SistemaRoute,
  TareasRoute: TareasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
